apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: kubepod-slave
spec:
  containers:
  - name: docker-container
    image: docker:20-dind
    tty: true
    privileged: true
    volumeMounts:
        - name: varrun
          mountPath: /var/run/