apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: kubepod-slave
    application: vnc-server
podRetention: onFailure
spec:
  containers:
  - name: docker-container
    image: docker:latest
    tty: true
    privileged: true
    command: ['docker', 'run', '-p', '80:80', 'httpd:latest']
    resources:
      limits:
        memory: "750Mi"
      requests:
        memory: "500Mi"
    volumeMounts:
      - name: unixsocket
        mountPath: /var/run
      - name: tmp
        mountPath: /tmp
    ports:
      - containerPort: 80
      - containerPort: 7080
      - containerPort: 5900
    imagePullSecrets:
      - name: artifact-registry
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/testimg.lock
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      exec:
        command:
        - touch
        - /tmp/testimg.lock
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
    - name: unixsocket
      hostPath:
        path: /var/run
    - name: tmp
      hostPath:
        path: /tmp