apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: kubepod-slave
    application: vnc-server
podRetention: onFailure
spec:
  containers:
  - name: docker-container
    image: docker:latest
    tty: true
    privileged: true
    command: ['docker', 'run', '-p', '80:80', '-v', '"$PWD":/usr/local/apache2/htdocs/', 'httpd:latest']
    resources:
      limits:
        memory: "750Mi"
      requests:
        memory: "500Mi"
    volumeMounts:
      - name: unixsocket
        mountPath: /var/run
      - name: tmp
        mountPath: /tmp
    ports:
      - containerPort: 58524
      - containerPort: 80
      - containerPort: 7080
    imagePullSecrets:
      - name: artifact-registry
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 1
      timeoutSeconds: 1
      ### checks if http-vnc connection is working
    readinessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 1
      timeoutSeconds: 1
  volumes:
    - name: unixsocket
      hostPath:
        path: /var/run
    - name: tmp
      hostPath:
        path: /tmp